# DEFAULT docker-compose.yml (VNC, Build-time Models) - REFERENCE ONLY
version: '3.8'
services:
  visomaster_default:
    image: ${DOCKERHUB_USERNAME:-your_dockerhub_username}/visomaster:latest
    container_name: visomaster_default_container
    restart: always
    ports:
      - "5901:5901" # VNC Port
    volumes:
      - /workspace:/workspace
    environment:
      - TZ=UTC
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: all