name: viso_env
channels:
  - pytorch
  - nvidia
  - conda-forge # Often good to include for other packages
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip
  - opencv # <--- ADD THIS (or ensure it's present)
  # Other conda packages...
  # - pip: # Keep pip section for pip-only packages
  #   - some-pip-package