# Workflow for DEFAULT build (VNC, Build-time Models) - Uses default/ folder
name: Build DEFAULT VisoMaster Image

on:
  push:
    branches:
      - main # Auto-build 'latest' on push to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-default:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Free up disk space
        run: |
          echo "Initial disk space:" && df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules || true
          docker image prune -af || true
          echo "Disk space after cleanup:" && df -h
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push DEFAULT Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./default/Dockerfile # Use default Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          compress: true