name: Build Small Default VisoMaster

on:
  push:
    branches: [ main ] # Or your default branch
    paths:
      - 's-def/**'
      - 'download_and_start.sh'
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Small Default image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context is the root
          file: ./s-def/Dockerfile # Specify the Dockerfile path
          push: true
          tags: remphan1618/godviso:s-def # Or your desired tag format