# Workflow for SMALL DEFAULT build (VNC, Runtime Models + Assets) - Uses s-def/ folder
name: Build SMALL DEFAULT VisoMaster Image

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build-s-def:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Free up disk space
        run: |
          echo "Initial disk space:" && df -h
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /usr/local/.ghcup /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules || true
          docker image prune -af || true
          echo "Disk space after cleanup:" && df -h
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push SMALL DEFAULT Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./s-def/Dockerfile # Use s-def Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:small-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:small-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          compress: true