# PRIMARY GitHub Actions Workflow (Builds standard VNC image)
name: Build and Push VisoMaster PRIMARY Docker Image

on:
  push:
    branches:
      - main # Trigger on push to main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PRIMARY Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Use primary Dockerfile in root
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max