# ALTERNATIVE GitHub Actions Workflow (Builds Portal image)
name: Build and Push VisoMaster ALT-PORTAL Docker Image

on:
  workflow_dispatch: # Allow manual triggering from GitHub Actions UI

jobs:
  build-and-push-portal:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ALT-PORTAL Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./alt/Dockerfile # Use Dockerfile from alt/ folder
          push: true
          tags: |
            # Use a specific tag for the portal version
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:portal-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/visomaster:portal-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max